### ISSUE TITLE
AttributeError: 'gdb.Symbol' object has no attribute 'is_artificial'

### ISSUE THREAD

**Issue by zkrx** [cyrus-and/gdb-dashboard#327]
Hi :)

I noticed since recently that I have the following error on breakpoint hit:
```
─── Variables ──────────────────────────────────────────────────────────────────────────────────────────────
Traceback (most recent call last):
  File "<string>", line 550, in render
  File "<string>", line 1568, in lines
  File "<string>", line 1623, in format_frame
  File "/usr/share/gdb/python/gdb/FrameDecorator.py", line 122, in frame_locals
    return args.fetch_frame_locals()
           ~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/share/gdb/python/gdb/FrameDecorator.py", line 288, in fetch_frame_locals
    elif sym.is_artificial:
         ^^^^^^^^^^^^^^^^^
AttributeError: 'gdb.Symbol' object has no attribute 'is_artificial'
```
I tested different (older) toolchains as well.

Quick search on Google shows that `is_artificial` was recently introduced in GDB:
```
January 18th, 2025: GDB 16.1 Released!
...
 Added the gdb.Symbol.is_artificial attribute. 
```
(from https://sourceware.org/gdb/ at the time of writing)

The GDB version I'm using is older, so that explains it:
```
[user@user fwv6_wt]$ arm-none-eabi-gdb --version
GNU gdb (GDB) 15.2
Copyright (C) 2024 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```
By the way, this is the arm version of GDB "officially" shipped by Arch Linux in its Extra repository:
https://archlinux.org/packages/extra/x86_64/arm-none-eabi-gdb/

I can look into upgrading GDB, but still: people working with cross-toolchains on other architectures may be stuck on older versions of GDB. So it might be worth fixing.

Anyway, thanks for the great work!

**Comment by cyrus-and** [comment]
I'm not even sure how to fix that honestly, I'm not using that attribute. Next time you have that error, try this GDB command:

```
(gdb) python print(gdb.FrameDecorator.FrameDecorator(gdb.selected_frame()).frame_locals())
```

What you get?

**Comment by zkrx** [comment]
This is what I get:
```
─── Variables ──────────────────────────────────────────────────────────────────────────────────────────────
Traceback (most recent call last):
  File "<string>", line 550, in render
  File "<string>", line 1568, in lines
  File "<string>", line 1623, in format_frame
  File "/usr/share/gdb/python/gdb/FrameDecorator.py", line 122, in frame_locals
    return args.fetch_frame_locals()
           ~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/share/gdb/python/gdb/FrameDecorator.py", line 288, in fetch_frame_locals
    elif sym.is_artificial:
         ^^^^^^^^^^^^^^^^^
AttributeError: 'gdb.Symbol' object has no attribute 'is_artificial'
────────────────────────────────────────────────────────────────────────────────────────────────────────────
>>> python print(gdb.FrameDecorator.FrameDecorator(gdb.selected_frame()).frame_locals())
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/share/gdb/python/gdb/FrameDecorator.py", line 122, in frame_locals
    return args.fetch_frame_locals()
           ~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/share/gdb/python/gdb/FrameDecorator.py", line 288, in fetch_frame_locals
    elif sym.is_artificial:
         ^^^^^^^^^^^^^^^^^
AttributeError: 'gdb.Symbol' object has no attribute 'is_artificial'
Error occurred in Python: 'gdb.Symbol' object has no attribute 'is_artificial'
>>> python print(gdb.FrameDecorator.FrameDecorator(gdb.selected_frame()))
<gdb.FrameDecorator.FrameDecorator object at 0x7447306d6210>
```

**Comment by zkrx** [comment]
I think it could simply have been a mismatch between two packages on the Arch Linux side:
```
[user fwv6_wt]$ pacman -Qi arm-none-eabi-gdb | grep Version
Version         : 15.2-2
[user fwv6_wt]$ pacman -Qi gdb-common | grep Version
Version         : 16.2-1
[user fwv6_wt]$ 
```
If I understand correctly, [arm-none-eabi-gdb](https://archlinux.org/packages/extra/x86_64/arm-none-eabi-gdb/) uses [gdb-common](https://archlinux.org/packages/extra/x86_64/gdb-common/) for its python bindings.

The package maintainers have just bumped arm-none-eabi-gdb to 16.2-1, so it's likely fixed now.

Thanks for helping!

**Comment by cyrus-and** [comment]
OK, yes, so this is not a bug with the dashboard. If you want, let others know if it works with 16.2-1.

**Comment by zkrx** [comment]
I upgrade my system and I no longer experience the issue.
```
arm-none-eabi-gdb --version
GNU gdb (GDB) 16.2
```
